# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd0dcb749c15a9ada040d81a6211f2f52f95a0141f5b864f50035d95bde4a2557ade7244fff45dad45cbf862ebd8a135c23ce8aa6a65f55b45f130fe571f7b9

test:
  secret_key_base: 9ebf3a4a61ab1bbe99d8962eb1c443bc2038998dfed37ee6230a146250d2e8474226c4c8639d1129420b4cd407db5266d4dc86f7c1779de40bb1478a24bf62bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
